/**
 * Dutch tender document structure guide
 * Describes how Dutch tender packages are structured to help AI parse and understand them.
 */

export interface TenderDocumentType {
  name: string;
  nameEn: string;
  description: string;
  typicalSections: string[];
  keywords: string[];
}

export const NL_TENDER_DOCUMENT_TYPES: TenderDocumentType[] = [
  {
    name: 'Aanbestedingsleidraad',
    nameEn: 'Procurement Guide',
    description:
      'Het hoofddocument van de aanbestedingsprocedure. Bevat alle procedurele regels, de planning, wijze van indienen, beoordelingsmethodiek, gunningscriteria en uitsluitingsgronden. Dit document is leidend voor de gehele procedure.',
    typicalSections: [
      'Begrippenlijst / Definities',
      'Beschrijving van de opdracht',
      'Procedureverloop en planning',
      'Wijze van indienen (TenderNed)',
      'Uitsluitingsgronden',
      'Geschiktheidseisen (ervaringseisen, financiele eisen, technische eisen)',
      'Gunningscriteria (EMVI / Beste prijs-kwaliteitverhouding / Laagste prijs)',
      'Beoordelingsmethodiek en wegingsfactoren',
      'Nota van Inlichtingen procedure',
      'Percelenregeling',
      'Geldigheidsduur inschrijving',
      'Standstill-termijn (Alcateltermijn)',
      'Klachtenregeling en bezwaarprocedure',
    ],
    keywords: [
      'aanbestedingsleidraad',
      'leidraad',
      'selectieleidraad',
      'inschrijvingsleidraad',
      'tenderleidraad',
      'proceduredocument',
      'procedurevoorschriften',
      'spelregels',
      'aanbestedingsregels',
    ],
  },
  {
    name: 'Beschrijvend Document',
    nameEn: 'Descriptive Document',
    description:
      'Beschrijft de inhoud, scope en context van de opdracht. Geeft een gedetailleerd overzicht van wat de aanbestedende dienst wil inkopen, de achtergrond, de doelstellingen en de verwachte resultaten.',
    typicalSections: [
      'Achtergrond en context',
      'Doelstelling van de opdracht',
      'Scope en afbakening',
      'Huidige situatie (ist-situatie)',
      'Gewenste situatie (soll-situatie)',
      'Randvoorwaarden',
      'Raakvlakken met andere projecten/contracten',
      'Verwachte looptijd en omvang',
    ],
    keywords: [
      'beschrijvend document',
      'opdrachtbeschrijving',
      'scopebeschrijving',
      'projectbeschrijving',
      'opdracht',
      'beschrijving',
      'scope of work',
      'werkbeschrijving',
    ],
  },
  {
    name: 'Programma van Eisen (PvE)',
    nameEn: 'Requirements Specification',
    description:
      'Het Programma van Eisen specificeert alle functionele en technische eisen waaraan de opdrachtnemer moet voldoen. Onderscheid tussen knock-out eisen (uitsluitend) en wensen (beoordelend). Eisen zijn doorgaans genummerd en voorzien van een prioriteit.',
    typicalSections: [
      'Functionele eisen',
      'Technische eisen',
      'Prestatie-eisen / KPI\'s',
      'Proceseisen',
      'Kwaliteitseisen',
      'Beveiligingseisen',
      'Duurzaamheidseisen',
      'Wensen (nice-to-have)',
      'Eisenmatrix / Compliance-matrix',
      'Minimale vereisten vs. gunningscriteria',
    ],
    keywords: [
      'programma van eisen',
      'pve',
      'eisenpakket',
      'eisenlijst',
      'eisen en wensen',
      'requirements',
      'functioneel ontwerp',
      'functionele specificatie',
      'technische specificatie',
      'specificaties',
      'compliance matrix',
      'eisenmatrix',
    ],
  },
  {
    name: 'Nota van Inlichtingen (NvI)',
    nameEn: 'Q&A Document / Information Notice',
    description:
      'Document met vragen van gegadigden en antwoorden van de aanbestedende dienst. Kan wijzigingen, aanvullingen of verduidelijkingen bevatten op de oorspronkelijke aanbestedingsstukken. De NvI prevaleert boven eerdere documenten. Er kunnen meerdere NvI\'s zijn.',
    typicalSections: [
      'Vragen en antwoorden (genummerd)',
      'Erratum / wijzigingen in aanbestedingsstukken',
      'Aangepaste planning',
      'Gewijzigde eisen',
      'Bijlagen bij NvI (gewijzigde documenten)',
    ],
    keywords: [
      'nota van inlichtingen',
      'nvi',
      'vragen en antwoorden',
      'inlichtingen',
      'q&a',
      'vraag en antwoord',
      'erratum',
      'verduidelijking',
      'wijzigingen',
      'rectificatie',
      'eerste nota',
      'tweede nota',
    ],
  },
  {
    name: 'Inschrijfbiljet',
    nameEn: 'Price Submission Form',
    description:
      'Het formulier waarop de inschrijver de prijs(opbouw) invult. Bevat het totaalbedrag, eventueel uitgesplitst in eenheidsprijzen, uurtarieven, bijkomende kosten. Moet exact conform het voorgeschreven format worden ingevuld en ondertekend.',
    typicalSections: [
      'Inschrijfsom (totaalbedrag excl. btw)',
      'Uitsplitsing per post / eenheid',
      'Uurtarieven per rol / functie',
      'Optionele posten',
      'Btw-berekening',
      'Ondertekening tekenbevoegde',
      'Geldigheidsduur aanbieding',
    ],
    keywords: [
      'inschrijfbiljet',
      'inschrijfstaat',
      'prijsopgave',
      'prijsbiljet',
      'prijsformulier',
      'tariefblad',
      'uurtarieven',
      'prijsinvulformulier',
      'inschrijfsom',
      'inschrijvingsformulier',
      'begrotingsformat',
    ],
  },
  {
    name: 'Model-bankgarantie',
    nameEn: 'Bank Guarantee Template',
    description:
      'Template voor de bankgarantie die de opdrachtnemer moet verstrekken. Bevat het garantiebedrag, de looptijd, de voorwaarden voor afroep en het format dat de bank moet volgen. De inschrijver moet dit model exact gebruiken.',
    typicalSections: [
      'Garantiebedrag en valuta',
      'Looptijd en einddatum',
      'Voorwaarden voor afroep',
      'Gegevens begunstigde (aanbestedende dienst)',
      'Gegevens principaal (opdrachtnemer)',
      'Verklaringen van de bank',
    ],
    keywords: [
      'bankgarantie',
      'model bankgarantie',
      'garantstelling',
      'garantie',
      'bank guarantee',
      'borgstelling',
      'uitvoeringsgarantie',
      'waarborgsom',
    ],
  },
  {
    name: 'Eigen Verklaring',
    nameEn: 'Self-Declaration Form',
    description:
      'Standaardformulier waarmee de inschrijver verklaart niet te vallen onder de uitsluitingsgronden (faillissement, fraude, witwassen, etc.) en te voldoen aan de geschiktheidseisen. Wordt bij Europese aanbestedingen vaak vervangen door het UEA.',
    typicalSections: [
      'Gegevens inschrijver',
      'Verklaring uitsluitingsgronden (art. 2.86 en 2.87 Aanbestedingswet)',
      'Verklaring geschiktheidseisen',
      'Verklaring beroep op derden',
      'Verklaring combinatievorming',
      'Ondertekening door tekenbevoegde',
    ],
    keywords: [
      'eigen verklaring',
      'zelfverklaring',
      'verklaring',
      'declaration',
      'uitsluitingsgronden',
      'self-declaration',
      'standaardformulier',
    ],
  },
  {
    name: 'UEA Formulier',
    nameEn: 'ESPD Form (European Single Procurement Document)',
    description:
      'Het Uniform Europees Aanbestedingsdocument (UEA) is het Europese standaardformulier voor zelfverklaring. Verplicht bij Europese aanbestedingen. Vervangt de Eigen Verklaring. Bevat verklaringen over uitsluitingsgronden, geschiktheid en selectiecriteria.',
    typicalSections: [
      'Deel I: Gegevens aanbestedingsprocedure',
      'Deel II: Gegevens ondernemer',
      'Deel III: Uitsluitingsgronden',
      'Deel IV: Selectiecriteria (geschiktheid)',
      'Deel V: Beperking aantal gekwalificeerde gegadigden',
      'Deel VI: Slotverklaringen',
    ],
    keywords: [
      'uea',
      'uniform europees aanbestedingsdocument',
      'espd',
      'european single procurement document',
      'europees formulier',
      'uea formulier',
      'espd formulier',
    ],
  },
  {
    name: 'Concept-overeenkomst',
    nameEn: 'Draft Contract',
    description:
      'Het concept van de overeenkomst die na gunning wordt gesloten. Bevat de contractvoorwaarden, rechten en plichten van partijen, looptijd, verlengingsopties, beeindigingsgronden en boeteclausules. Door in te schrijven accepteert de inschrijver in principe deze voorwaarden.',
    typicalSections: [
      'Partijen en definities',
      'Voorwerp van de overeenkomst',
      'Looptijd en verlengingsopties',
      'Vergoeding en betalingsvoorwaarden',
      'Intellectueel eigendom',
      'Geheimhouding en privacy (AVG/GDPR)',
      'Aansprakelijkheid en verzekeringen',
      'Beeindiging en ontbinding',
      'Boeteclausules / malus',
      'Geschillenbeslechting',
      'Toepasselijk recht',
      'SLA en KPI\'s',
    ],
    keywords: [
      'concept-overeenkomst',
      'conceptovereenkomst',
      'raamovereenkomst',
      'overeenkomst',
      'contract',
      'conceptcontract',
      'dienstverleningsovereenkomst',
      'leveringsovereenkomst',
      'mantelovereenkomst',
      'raamcontract',
      'deelovereenkomst',
    ],
  },
  {
    name: 'ARW 2016',
    nameEn: 'Procurement Regulations for Works 2016',
    description:
      'Het Aanbestedingsreglement Werken 2016 is specifiek van toepassing op aanbesteding van werken (bouwprojecten). Bevat procedurele regels voor de aanbesteding van overheidsopdrachten voor werken, inclusief het proces-verbaal van aanwijzing, de inschrijfstaat en het bestek.',
    typicalSections: [
      'Toepasselijkheid en definities',
      'Selectieprocedure',
      'Aanwijzing (schouw)',
      'Nota van Inlichtingen bij werken',
      'Inschrijfstaat en inschrijfbiljet',
      'Opening van inschrijvingen',
      'Beoordeling en gunning',
      'Proces-verbaal van aanwijzing',
      'Besteksbepalingen',
    ],
    keywords: [
      'arw 2016',
      'arw',
      'aanbestedingsreglement werken',
      'reglement werken',
      'werken',
      'bouwwerk',
      'bestek',
      'besteksbepalingen',
      'inschrijfstaat',
      'proces-verbaal van aanwijzing',
    ],
  },
  {
    name: 'UAV 2012 / UAV-GC 2005',
    nameEn: 'Standard Conditions for Works / Design & Build',
    description:
      'Uniforme Administratieve Voorwaarden voor de uitvoering van werken (UAV 2012) of geintegreerde contracten (UAV-GC 2005). Standaardvoorwaarden die de relatie tussen opdrachtgever en aannemer regelen bij bouwprojecten. De UAV 2012 is voor traditionele contracten, de UAV-GC 2005 voor design & build.',
    typicalSections: [
      'Verplichtingen van de aannemer',
      'Verplichtingen van de opdrachtgever',
      'Werkzaamheden en uitvoeringstermijn',
      'Betaling en meer/minderwerk',
      'Wijzigingen en besteksafwijkingen',
      'Oplevering en onderhoudstermijn',
      'Aansprakelijkheid na oplevering',
      'Geschillenbeslechting (Raad van Arbitrage)',
    ],
    keywords: [
      'uav 2012',
      'uav-gc 2005',
      'uav',
      'uav-gc',
      'uniforme administratieve voorwaarden',
      'algemene voorwaarden werken',
      'design & build',
      'geintegreerd contract',
      'dbfmo',
      'design build',
      'raad van arbitrage',
    ],
  },
  {
    name: 'ARVODI / ARIV',
    nameEn: 'Standard Conditions for Services / IT',
    description:
      'Algemene Rijksvoorwaarden voor het verstrekken van opdrachten tot het verrichten van Diensten (ARVODI) of voor Informatievoorziening (ARIV). Standaardvoorwaarden van de Rijksoverheid voor dienstverlening en IT-opdrachten. Worden vaak van toepassing verklaard bij Rijksaanbestedingen.',
    typicalSections: [
      'Definities en toepasselijkheid',
      'Uitvoering van de opdracht',
      'Medewerking door opdrachtgever',
      'Intellectuele eigendomsrechten',
      'Geheimhouding en beveiliging',
      'Aansprakelijkheid',
      'Overmacht',
      'Betaling',
      'Beeindiging',
      'Overdracht en uitbesteding',
      'Toepasselijk recht en geschillen',
    ],
    keywords: [
      'arvodi',
      'ariv',
      'algemene rijksvoorwaarden',
      'rijksvoorwaarden',
      'rijksoverheid voorwaarden',
      'algemene voorwaarden diensten',
      'voorwaarden informatievoorziening',
      'arbit',
      'algemene voorwaarden it',
      'rijksinkoop',
    ],
  },
];
